In [1]:
# introduction to numpy ===>
# why numpy is better than list
# 1. same data type (array)
#2. memory consume ===> np less and list high 
# compution power ==> numpy high and lish less
# function numpy high list less

In [2]:
import numpy as np
a = [1,2,3,4]
type(a)

list

In [3]:
b = np.array(a)
b

array([1, 2, 3, 4])

In [4]:
type(b)

numpy.ndarray

In [5]:
l = []
n = int(input())
for i in range(n):
    a = int(input("Enter the number : "))
    l.append(a)
print(type(l))
array = np.array(l)
print(type(array))

3
Enter the number : 1
Enter the number : 2
Enter the number : 34
<class 'list'>
<class 'numpy.ndarray'>


# Check for shape and size 

In [6]:
#shape ==> n(rows) , n(columns)
# size ==> number of elements ==> n(rows)*n(columns)

In [7]:
print("Total shape : ", b.shape)

Total shape :  (4,)


In [8]:
b.size

4

In [9]:
a = [[1,2,3],[2,3,4],[3,4,5]]
b = np.array(a)

In [10]:
b.shape

(3, 3)

In [11]:
b.size

9

In [12]:
#image ==> pixels ===> (0-255) ===> 0 - (black), 255 - (white)
# convert ===> grayscale image ===>
# image(Pixels) ===> normalization(0-1)===> 0px (black) 1px (white)

# 0,1 ===> Neoron system

# Matrix ===> rows, column
# symmatrix matrix ===> n(row) = n(columns)
# Asymmatrix matrix ===> n(row) != n(columns)
# diagonal elements = [(1,1),(2,2),(3,3)...(n,n)]

# 1. zeros() ===> it will create an array in which all the elements are zero.

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
 a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.shape(a)

(3, 4)

# 2. ones() ===> it will create an array in which all the values are one

# 3. eye() ===> this function will create an array of diagonal elements

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.eye(1)

array([[1.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])