# diag ===> this function create a two dimensional array with all the diagonal elements as the given value and rest are zero

In [4]:
import numpy as np
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# randint ===> this function is used to generate a random number between a given range

# syntax = randint(min,max,total_num)

In [6]:
a = np.random.randint(1,10,3)
a

array([2, 3, 9])

# rand() ===> this function is used to genereate a random number between 0 to 1

# syntax = rand(number of values)

In [9]:
a = np.random.rand(5)
a

array([0.07733772, 0.05100379, 0.52103562, 0.57303189, 0.29084741])

# randn() ==> this function is used to generate a random number from -3 to close 3. this may return positive and negative number as well

In [11]:
a = np.random.randn(5)
a

array([ 1.55219471,  0.32662268, -0.81531108,  0.7005734 ,  0.1293878 ])

# Reshaping the data

In [19]:
# n(rows) * n(columns) = total number of element 
a = np.random.randint(1,50,12)
a

array([ 3, 34,  2,  1, 17, 37, 41, 42, 41, 18, 46, 13])

In [20]:
a.shape

(12,)

In [21]:
a = a.reshape(2,6)
a

array([[ 3, 34,  2,  1, 17, 37],
       [41, 42, 41, 18, 46, 13]])

In [22]:
a = a .reshape(3,4)
a

array([[ 3, 34,  2,  1],
       [17, 37, 41, 42],
       [41, 18, 46, 13]])

In [23]:
a = np.random.randint(1,100,64)
a

array([95, 64, 65, 71, 47, 41, 83, 74, 89, 71, 80, 99, 57, 76, 10, 13, 64,
       51, 79, 34, 31, 90, 87, 32, 80,  3, 57,  4, 75, 58,  3, 50, 79, 47,
       91,  3, 27, 12, 10, 35, 20, 67, 50, 82, 61,  2, 34, 93,  6, 40, 10,
       52,  9, 11,  6,  2, 89, 43, 44, 30, 37, 95, 16,  4])

In [24]:
a.shape

(64,)

In [25]:
a.reshape(2,32)

array([[95, 64, 65, 71, 47, 41, 83, 74, 89, 71, 80, 99, 57, 76, 10, 13,
        64, 51, 79, 34, 31, 90, 87, 32, 80,  3, 57,  4, 75, 58,  3, 50],
       [79, 47, 91,  3, 27, 12, 10, 35, 20, 67, 50, 82, 61,  2, 34, 93,
         6, 40, 10, 52,  9, 11,  6,  2, 89, 43, 44, 30, 37, 95, 16,  4]])

In [26]:
a.reshape(32,2)

array([[95, 64],
       [65, 71],
       [47, 41],
       [83, 74],
       [89, 71],
       [80, 99],
       [57, 76],
       [10, 13],
       [64, 51],
       [79, 34],
       [31, 90],
       [87, 32],
       [80,  3],
       [57,  4],
       [75, 58],
       [ 3, 50],
       [79, 47],
       [91,  3],
       [27, 12],
       [10, 35],
       [20, 67],
       [50, 82],
       [61,  2],
       [34, 93],
       [ 6, 40],
       [10, 52],
       [ 9, 11],
       [ 6,  2],
       [89, 43],
       [44, 30],
       [37, 95],
       [16,  4]])

In [27]:
a.reshape(16,4)

array([[95, 64, 65, 71],
       [47, 41, 83, 74],
       [89, 71, 80, 99],
       [57, 76, 10, 13],
       [64, 51, 79, 34],
       [31, 90, 87, 32],
       [80,  3, 57,  4],
       [75, 58,  3, 50],
       [79, 47, 91,  3],
       [27, 12, 10, 35],
       [20, 67, 50, 82],
       [61,  2, 34, 93],
       [ 6, 40, 10, 52],
       [ 9, 11,  6,  2],
       [89, 43, 44, 30],
       [37, 95, 16,  4]])

In [28]:
a.reshape(4,16)

array([[95, 64, 65, 71, 47, 41, 83, 74, 89, 71, 80, 99, 57, 76, 10, 13],
       [64, 51, 79, 34, 31, 90, 87, 32, 80,  3, 57,  4, 75, 58,  3, 50],
       [79, 47, 91,  3, 27, 12, 10, 35, 20, 67, 50, 82, 61,  2, 34, 93],
       [ 6, 40, 10, 52,  9, 11,  6,  2, 89, 43, 44, 30, 37, 95, 16,  4]])

In [29]:
a.reshape(8,8)

array([[95, 64, 65, 71, 47, 41, 83, 74],
       [89, 71, 80, 99, 57, 76, 10, 13],
       [64, 51, 79, 34, 31, 90, 87, 32],
       [80,  3, 57,  4, 75, 58,  3, 50],
       [79, 47, 91,  3, 27, 12, 10, 35],
       [20, 67, 50, 82, 61,  2, 34, 93],
       [ 6, 40, 10, 52,  9, 11,  6,  2],
       [89, 43, 44, 30, 37, 95, 16,  4]])

# principal of -1

In [31]:
a = a.reshape(-1,4)
a

array([[95, 64, 65, 71],
       [47, 41, 83, 74],
       [89, 71, 80, 99],
       [57, 76, 10, 13],
       [64, 51, 79, 34],
       [31, 90, 87, 32],
       [80,  3, 57,  4],
       [75, 58,  3, 50],
       [79, 47, 91,  3],
       [27, 12, 10, 35],
       [20, 67, 50, 82],
       [61,  2, 34, 93],
       [ 6, 40, 10, 52],
       [ 9, 11,  6,  2],
       [89, 43, 44, 30],
       [37, 95, 16,  4]])

In [33]:
a = a.reshape(4,-1)
a

array([[95, 64, 65, 71, 47, 41, 83, 74, 89, 71, 80, 99, 57, 76, 10, 13],
       [64, 51, 79, 34, 31, 90, 87, 32, 80,  3, 57,  4, 75, 58,  3, 50],
       [79, 47, 91,  3, 27, 12, 10, 35, 20, 67, 50, 82, 61,  2, 34, 93],
       [ 6, 40, 10, 52,  9, 11,  6,  2, 89, 43, 44, 30, 37, 95, 16,  4]])

# seed function() ==> we know that randint function generates random numbers. everytime we run the program, new set of random number is generated. so solve this problem we wi;; use seed function

In [42]:
np.random.seed(5)
a = np.random.randint(1,10,3)
# np.random.seed(5)
a

array([4, 7, 7])

# view vs copy ===> when we slice a sub- array from an array,, it may be done by two ways

In [45]:
a = np.array([10,20,30,40,50,60,70,80])

In [46]:
b = a[3:6]
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# copy

In [49]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a,b

(array([10, 20, 30, 40, 50, 60, 70, 80]), array([0, 0, 0]))

# conditional statements

In [50]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [52]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [53]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [54]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

# operation on array 

In [55]:
a = np.arange(1,5)
a*2

array([2, 4, 6, 8])

In [56]:
a+2

array([3, 4, 5, 6])

In [57]:
a**2

array([ 1,  4,  9, 16])

In [60]:
b = np.array([1,2,3,4]).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [61]:
a+b

array([[2, 4],
       [6, 8]])

In [62]:
b-a

array([[0, 0],
       [0, 0]])

In [63]:
b/a

array([[1., 1.],
       [1., 1.]])

In [64]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [65]:
a.dot(b) #matrix multipltion 

array([[ 7, 10],
       [15, 22]])

# some more important numpy function

In [66]:
a = np.array([1,2,3,4,5,6])
np.min(a) #min value

1

In [67]:
np.max(a) #max value 

6

In [68]:
np.argmin(a) #min value index

0

In [69]:
np.argmax(a) #max value index

5

In [70]:
np.sqrt(a) #square 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [71]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

# linspace ==> this function returns value between a given range and with a same gap between consicutive elements

In [72]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# np.unique(arr,return_index=true,return_count= true)

## return 3 array 1. the array with unique values 2. the array with respective index value 3. the array with counting of frequency

In [73]:
a = np.array([10,20,30,40,10,20,30,40,50])
np.unique(a,return_index = True, return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 8], dtype=int64),
 array([2, 2, 2, 2, 1], dtype=int64))

# horizontal and vertical stacking 

In [74]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [75]:
b

array([5, 6, 7, 8])

In [76]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [80]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])