In [1]:
import numpy as np #importing numpy

In [2]:
# array using numpy
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# 10 random integer
a = np.random.randint(1,100,10)
a

array([91, 94, 25, 38,  1,  5, 37, 75, 97, 77])

In [6]:
# element in range 10-20
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
# 1D array 
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# reshape 1D array in 3*3
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# array number between 0 and 1
a = np.random.rand(9)
a

array([0.62277683, 0.04291575, 0.42237006, 0.37741366, 0.26123837,
       0.65852731, 0.11147053, 0.44492686, 0.8309432 ])

In [15]:
# reshape to 2D array
a.reshape(3,3)

array([[0.62277683, 0.04291575, 0.42237006],
       [0.37741366, 0.26123837, 0.65852731],
       [0.11147053, 0.44492686, 0.8309432 ]])

In [16]:
# horizontal stack
np.hstack(a)

array([0.62277683, 0.04291575, 0.42237006, 0.37741366, 0.26123837,
       0.65852731, 0.11147053, 0.44492686, 0.8309432 ])

In [18]:
#vertical stack
np.vstack(a)

array([[0.62277683],
       [0.04291575],
       [0.42237006],
       [0.37741366],
       [0.26123837],
       [0.65852731],
       [0.11147053],
       [0.44492686],
       [0.8309432 ]])

In [24]:
# 5 10 times 
a = np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])